import { Request, Response, NextFunction } from 'express';
import { productResearchSchema } from '../validators/report';
import { cacheService } from '../services/cache';
import { getShoppingResults } from '../services/serpapi';
import { getTrends } from '../services/trends';
import { getExchangeRates } from '../services/exchange';
import { runGroqWithRetry } from '../services/groq';
import { Report } from '../models/Report';
import { ZodError } from 'zod';

const PRODUCT_SYSTEM_PROMPT = `You are a world-class e-commerce market analyst. 
Given a niche and country, perform deep research using provided data (shopping results, trends). 
Respond ONLY with a valid JSON object (no markdown, no code fences) that exactly follows this structure:
{
  "market_score": number (0-100),
  "pricing_engine": [
    { 
      "title": string, 
      "image": string, 
      "price": number, 
      "currency": string, 
      "estimated_cost": number, 
      "estimated_profit": number, 
      "reviews": number 
    }
  ],
  "competitors": [ 
    { "name": string, "strength": string, "weakness": string } 
  ] (max 10),
  "market_gap": [ 
    { "insight": string, "icon": string } 
  ] (exactly 3),
  "personas": [ 
    { "name": string, "avatar": string, "description": string, "ads_channel": string } 
  ] (exactly 3),
  "launch_plan": [ 
    { "day": number, "task": string } 
  ] (30 days, day 1 to 30),
  "risks": [ string ],
  "chart_data": { 
    "demand_forecast": number[], 
    "competitor_market_share": [ 
      { "name": string, "value": number } 
    ] 
  }
}

IMPORTANT: 
- market_score must be realistic (40-95 range)
- pricing_engine must have exactly 10 products with realistic prices
- estimated_cost should be 40-70% of price
- estimated_profit = price - estimated_cost
- All numbers must be positive integers where applicable
- icons for market_gap should be relevant emojis (🔥💰📊🎯⚡🛡️📈💡)
- avatars for personas should be emojis (👨‍💼👩‍💻🧑‍🎨👨‍🔧👩‍🚀🧑‍🍳)
- launch_plan must have exactly 30 items, days 1-30
- chart_data.demand_forecast must have 12 numbers (monthly)
- chart_data.competitor_market_share must sum to 100`;

function generateProductMarkdown(analysis: any, niche: string, country: string): string {
  const countryNames: Record<string, string> = {
    us: 'United States 🇺🇸',
    pk: 'Pakistan 🇵🇰',
    gb: 'United Kingdom 🇬🇧',
    ae: 'United Arab Emirates 🇦🇪',
    sa: 'Saudi Arabia 🇸🇦',
  };

  return `# 🚀 Product Research Report: ${niche}
## Target Market: ${countryNames[country] || country.toUpperCase()}

---

## 📊 Market Score: **${analysis.market_score}/100**

${analysis.market_score >= 80 ? '🔥 **HIGH POTENTIAL** - This niche shows strong signals for profitability.' : 
  analysis.market_score >= 60 ? '📈 **MODERATE POTENTIAL** - Good opportunity with manageable competition.' : 
  '⚠️ **CAUTIOUS** - High competition or low demand detected.'}

---

## 💰 Pricing Engine
${analysis.pricing_engine?.map((p: any, i: number) => 
  `### ${i + 1}. ${p.title}
- **Price:** $${p.price} | **Est. Cost:** $${p.estimated_cost} | **Est. Profit:** $${p.estimated_profit}
- **Reviews:** ${p.reviews} ⭐`
).join('\n\n') || 'No pricing data available'}

---

## 🏆 Top Competitors
${analysis.competitors?.map((c: any, i: number) => 
  `### ${i + 1}. ${c.name}
- **Strength:** ${c.strength}
- **Weakness:** ${c.weakness}`
).join('\n\n') || 'No competitor data available'}

---

## 🎯 Market Gaps (Opportunities)
${analysis.market_gap?.map((g: any, i: number) => 
  `### ${g.icon} Gap ${i + 1}
${g.insight}`
).join('\n\n') || 'No market gap data available'}

---

## 👥 Customer Personas
${analysis.personas?.map((p: any, i: number) => 
  `### ${p.avatar} Persona ${i + 1}: ${p.name}
- **Description:** ${p.description}
- **Best Ads Channel:** ${p.ads_channel}`
).join('\n\n') || 'No persona data available'}

---

## 📅 30-Day Launch Plan
${analysis.launch_plan?.map((d: any) => 
  `### Day ${d.day}
${d.task}`
).join('\n') || 'No launch plan available'}

---

## ⚠️ Risks & Mitigations
${analysis.risks?.map((r: string) => `- ${r}`).join('\n') || 'No risks identified'}

---

*Report generated by MarketMuse AI PRO MAX ULTRA - $99/report*`;
}

export const createProductReport = async (req: Request, res: Response, next: NextFunction) => {
  try {
    // Validate input
    const { niche, country } = productResearchSchema.parse(req.body);
    const countryUpper = country.toUpperCase();
    
    // Check cache
    const cacheKey = `product_report_${niche}_${country}`;
    const cached = cacheService.get(cacheKey);
    if (cached) {
      console.log('📦 Returning cached product report');
      return res.json(cached);
    }

    console.log(`🔍 Starting product research: "${niche}" in ${countryUpper}`);

    // Parallel data fetching
    const [shoppingData, trendsData, exchangeRates] = await Promise.all([
      getShoppingResults(niche, country),
      getTrends(niche, countryUpper),
      getExchangeRates(),
    ]);

    // Extract relevant shopping items for Groq
    const products = (shoppingData as any).shopping_results?.slice(0, 10).map((p: any) => ({
      title: p.title || 'Unknown Product',
      price: p.extracted_price || p.price || 0,
      source: p.source || 'Unknown',
      reviews: p.rating || 0,
      image: p.thumbnail || '',
    })) || [];

    // Build user message with real data
    const userMessage = `Niche: ${niche}
Country: ${country} (${countryUpper})
Exchange Rates: ${JSON.stringify(exchangeRates)}

Top Shopping Results:
${JSON.stringify(products, null, 2)}

12-Month Trends Data (first 6 months):
${JSON.stringify(trendsData.slice(0, 6), null, 2)}

Please analyze this market and provide complete JSON response.`;

    // Get AI analysis
    console.log('🤖 Requesting Groq analysis...');
    const groqResponse = await runGroqWithRetry(PRODUCT_SYSTEM_PROMPT, userMessage);
    
    // Parse JSON from Groq
    let analysis;
    try {
      const cleaned = groqResponse.replace(/```json|```/g, '').trim();
      analysis = JSON.parse(cleaned);
    } catch (parseError) {
      console.error('❌ Failed to parse Groq JSON:', groqResponse.substring(0, 200));
      throw new Error('AI response format invalid. Please try again.');
    }

    // Validate required fields
    if (!analysis.market_score || !analysis.pricing_engine || !analysis.competitors) {
      throw new Error('AI response missing required fields');
    }

    // Generate markdown
    const markdown = generateProductMarkdown(analysis, niche, country);

    // Build chart data for frontend
    const charts = {
      trends: trendsData,
      marketScore: analysis.market_score,
      demandForecast: analysis.chart_data?.demand_forecast || [],
      competitorShare: analysis.chart_data?.competitor_market_share || [],
      pricing: analysis.pricing_engine || [],
    };

    // Save to database
    const report = await Report.create({
      type: 'product',
      niche,
      country,
      value: '$99',
      data: analysis,
      markdown,
      charts,
    });

    console.log('✅ Product report generated:', report._id);

    const result = {
      id: report._id,
      type: report.type,
      niche: report.niche,
      country: report.country,
      value: report.value,
      data: analysis,
      markdown: report.markdown,
      charts: charts,
      createdAt: report.createdAt,
    };

    // Cache for 24 hours
    cacheService.set(cacheKey, result, 86400);

    return res.status(201).json(result);

  } catch (err) {
    // Handle validation errors
    if (err instanceof ZodError) {
      return res.status(400).json({ 
        error: 'Validation failed', 
        details: err.errors.map(e => ({ field: e.path.join('.'), message: e.message }))
      });
    }
    
    // Pass other errors to error handler
    next(err);
  }
};

export const getProductReport = async (req: Request, res: Response, next: NextFunction) => {
  try {
    const report = await Report.findById(req.params.id);
    if (!report) {
      return res.status(404).json({ error: 'Report not found' });
    }
    if (report.type !== 'product') {
      return res.status(400).json({ error: 'This is not a product report' });
    }
    res.json(report);
  } catch (err) {
    next(err);
  }
};
