import { Request, Response, NextFunction } from 'express';
import { productResearchSchema } from '../validators/report';
import { cacheService } from '../services/cache';
import { getShoppingResults } from '../services/serpapi';
import { getTrends } from '../services/trends';
import { getExchangeRates } from '../services/exchange';
import { runGroqWithRetry } from '../services/groq';
import { Report } from '../models/Report';
import { ZodError } from 'zod';

// Robust JSON extraction with fallback for truncated responses
const extractJSON = (raw: string): any => {
  let cleaned = raw.replace(/```json|```/g, '').trim();
  const startIdx = cleaned.indexOf('{');
  const endIdx = cleaned.lastIndexOf('}');
  if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
    cleaned = cleaned.substring(startIdx, endIdx + 1);
  }
  try {
    return JSON.parse(cleaned);
  } catch (err) {
    console.log('⚠️ Initial parse failed, attempting repair...');
    // Try to fix truncated JSON by counting braces and closing them
    let openBraces = 0;
    for (const ch of cleaned) {
      if (ch === '{') openBraces++;
      else if (ch === '}') openBraces--;
    }
    while (openBraces > 0) {
      cleaned += '}';
      openBraces--;
    }
    // Also fix common issues
    cleaned = cleaned
      .replace(/,\s*}/g, '}')
      .replace(/,\s*]/g, ']');
    try {
      return JSON.parse(cleaned);
    } catch (e) {
      console.error('❌ extractJSON failed. Cleaned string:', cleaned.substring(0, 500));
      throw new Error('AI response is not valid JSON. Please try again.');
    }
  }
};

const PRODUCT_SYSTEM_PROMPT = `You are an e-commerce product strategist. Analyze the niche, shopping data, and trends. Return ONLY valid JSON with:
{
  "market_score": number (0-100),
  "market_summary": string,
  "pricing_engine": [{ "title": string, "price": number, "estimated_cost": number, "estimated_profit": number, "reviews": number, "source": string }] (5 items from real data),
  "competitors": [{ "name": string, "strengths": [string], "weaknesses": [string] }] (5),
  "market_gaps": [{ "insight": string, "icon": string }] (3),
  "personas": [{ "name": string, "avatar": string, "demographics": string, "goals": string, "pain_points": string, "buying_triggers": string, "preferred_channels": [string] }] (3),
  "launch_plan": [{ "day": number, "task": string, "category": string }] (15 items, specific to niche),
  "profit_forecast": { "monthly_revenue_estimate": number, "monthly_profit_estimate": number, "break_even_months": number },
  "risks": [string] (3),
  "chart_data": { "demand_forecast": number[], "competitor_market_share": [{ "name": string, "value": number }] }
}`;

function generateProductMarkdown(analysis: any, niche: string, country: string): string {
  const countryNames: Record<string, string> = {
    us: 'United States 🇺🇸', pk: 'Pakistan 🇵🇰', gb: 'United Kingdom 🇬🇧', ae: 'United Arab Emirates 🇦🇪', sa: 'Saudi Arabia 🇸🇦',
  };

  return `# 🚀 Product Research Report: ${niche}
## Target Market: ${countryNames[country] || country.toUpperCase()}

## 📊 Market Score: **${analysis.market_score}/100**
${analysis.market_summary || ''}

## 💰 Pricing Engine
${analysis.pricing_engine?.map((p: any, i: number) => `### ${i + 1}. ${p.title}\n- Price: $${p.price} | Cost: $${p.estimated_cost} | Profit: $${p.estimated_profit}\n- Reviews: ${p.reviews} ⭐`).join('\n\n') || 'N/A'}

## 🏆 Competitors
${analysis.competitors?.map((c: any, i: number) => `### ${c.name}\n- Strengths: ${c.strengths?.join(', ')}\n- Weaknesses: ${c.weaknesses?.join(', ')}`).join('\n\n') || 'N/A'}

## 🎯 Market Gaps
${analysis.market_gap?.map((g: any) => `${g.icon} ${g.insight}`).join('\n') || 'N/A'}

## 👥 Personas
${analysis.personas?.map((p: any) => `### ${p.avatar} ${p.name}\n- ${p.demographics}\n- Goals: ${p.goals}\n- Pain: ${p.pain_points}\n- Channels: ${p.preferred_channels?.join(', ')}`).join('\n\n') || 'N/A'}

## 📅 15-Day Launch Plan
${analysis.launch_plan?.map((d: any) => `Day ${d.day} (${d.category}): ${d.task}`).join('\n') || 'N/A'}

## 💸 Profit Forecast
- Revenue: $${analysis.profit_forecast?.monthly_revenue_estimate || 0}/mo
- Profit: $${analysis.profit_forecast?.monthly_profit_estimate || 0}/mo
- Break-even: ${analysis.profit_forecast?.break_even_months || 'N/A'} months

## ⚠️ Risks
${analysis.risks?.map((r: string) => `- ${r}`).join('\n') || 'None'}

*Generated by MarketMuse AI PRO MAX ULTRA – $99/report*`;
}

export const createProductReport = async (req: Request, res: Response, next: NextFunction) => {
  try {
    const { niche, country } = productResearchSchema.parse(req.body);
    const countryUpper = country.toUpperCase();
    const cacheKey = `product_report_${niche}_${country}`;
    const cached = cacheService.get(cacheKey);
    if (cached) { console.log('📦 Returning cached'); return res.json(cached); }

    console.log(`🔍 Product research: "${niche}" in ${countryUpper}`);
    const [shoppingData, trendsData, exchangeRates] = await Promise.all([
      getShoppingResults(niche, country), getTrends(niche, countryUpper), getExchangeRates()
    ]);

    const products = (shoppingData as any).shopping_results?.slice(0, 3).map((p: any) => ({
      title: p.title || 'Unknown', price: p.extracted_price || p.price || 0, source: p.source || 'Unknown', reviews: p.rating || 0
    })) || [];

    const userMessage = `Niche: ${niche}\nCountry: ${country}\nShopping Data: ${JSON.stringify(products)}\nTrends: ${JSON.stringify(trendsData.slice(0, 6))}\nReturn JSON.`;

    console.log('🤖 Requesting Groq...');
    const groqResponse = await runGroqWithRetry(PRODUCT_SYSTEM_PROMPT, userMessage);
    const analysis = extractJSON(groqResponse);

    if (!analysis.market_score) throw new Error('Missing market_score');
    const markdown = generateProductMarkdown(analysis, niche, country);

    const report = await Report.create({ type: 'product', niche, country, value: '$99', data: analysis, markdown, charts: {} });
    console.log('✅ Product report:', report._id);

    const result = { id: report._id, type: report.type, niche, country, value: '$99', data: analysis, markdown, createdAt: report.createdAt };
    cacheService.set(cacheKey, result, 86400);
    return res.status(201).json(result);
  } catch (err) {
    if (err instanceof ZodError) return res.status(400).json({ error: 'Validation failed', details: err.errors });
    next(err);
  }
};

export const getProductReport = async (req: Request, res: Response, next: NextFunction) => {
  try {
    const report = await Report.findById(req.params.id);
    if (!report || report.type !== 'product') return res.status(404).json({ error: 'Not found' });
    res.json(report);
  } catch (err) { next(err); }
};
