import { Request, Response, NextFunction } from 'express';
import { seoReportSchema } from '../validators/report';
import { cacheService } from '../services/cache';
import { getSearchResults, getKeywordSuggestions } from '../services/serpapi';
import { getTrends } from '../services/trends';
import { runGroqWithRetry } from '../services/groq';
import { Report } from '../models/Report';
import { ZodError } from 'zod';

// Robust JSON extraction with fallback
const extractJSON = (raw: string): any => {
  let cleaned = raw.replace(/```json|```/g, '').trim();
  const startIdx = cleaned.indexOf('{');
  const endIdx = cleaned.lastIndexOf('}');
  if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
    cleaned = cleaned.substring(startIdx, endIdx + 1);
  }
  try {
    return JSON.parse(cleaned);
  } catch (err) {
    console.log('⚠️ Initial parse failed, attempting repair...');
    let openBraces = 0;
    for (const ch of cleaned) { if (ch === '{') openBraces++; else if (ch === '}') openBraces--; }
    while (openBraces > 0) { cleaned += '}'; openBraces--; }
    cleaned = cleaned.replace(/,\s*}/g, '}').replace(/,\s*]/g, ']');
    try {
      return JSON.parse(cleaned);
    } catch (e) {
      console.error('❌ extractJSON failed. Cleaned string:', cleaned.substring(0, 500));
      throw new Error('AI response is not valid JSON. Please try again.');
    }
  }
};

const SEO_SYSTEM_PROMPT = `You are an SEO director. Given a niche, country, SERP data, and trends, create a comprehensive SEO strategy. Return ONLY valid JSON with:
{
  "trend_score": "Seasonal" or "Evergreen",
  "trend_insight": string,
  "keywords": [{ "keyword": string, "volume": number, "kd": number, "cpc": number, "intent": string }] (20 items, varying volumes),
  "serp_analysis": [{ "position": number, "title": string, "url": string, "da": number, "word_count": number, "backlinks": number, "strengths": string, "weaknesses": string }] (5 items from real data),
  "content_calendar": [{ "week": number, "title": string, "keyword": string, "content_type": string, "word_count_target": number, "outline": [string] }] (12 weeks),
  "backlink_strategy": {
    "overview": string,
    "target_sites": [{ "site": string, "type": string, "contact_method": string, "reason": string }] (5 specific sites),
    "guest_post_topics": [string] (3),
    "broken_link_opportunities": [string] (2),
    "resource_page_targets": [string] (3),
    "outreach_email_template": string
  },
  "onpage_checklist": [string] (10 items),
  "chart_data": { "trend_12m": number[], "keyword_difficulty_distribution": { "easy": number, "medium": number, "hard": number } }
}`;

function generateSEOMarkdown(analysis: any, niche: string, country: string): string {
  const countryNames: Record<string, string> = { us: '🇺🇸 US', pk: '🇵🇰 PK', gb: '🇬🇧 GB', ae: '🇦🇪 AE', sa: '🇸🇦 SA' };
  const bs = analysis.backlink_strategy;
  return `# 🔍 SEO Report: ${niche}
## Target: ${countryNames[country] || country.toUpperCase()}

## 📊 Trend: ${analysis.trend_score}
${analysis.trend_insight || ''}

## 🏆 Keywords
${analysis.keywords?.map((k: any) => `- ${k.keyword} (Vol: ${k.volume}, KD: ${k.kd}, CPC: $${k.cpc}, Intent: ${k.intent})`).join('\n') || 'N/A'}

## 📈 SERP Analysis
${analysis.serp_analysis?.map((s: any) => `### #${s.position} ${s.title}\n- URL: ${s.url}\n- DA: ${s.da}, Words: ${s.word_count}, Backlinks: ${s.backlinks}\n- Strengths: ${s.strengths}\n- Weaknesses: ${s.weaknesses}`).join('\n\n') || 'N/A'}

## 📅 Content Calendar (12 Weeks)
${analysis.content_calendar?.map((c: any) => `### Week ${c.week}: ${c.title}\n- Keyword: ${c.keyword}, Type: ${c.content_type}, Words: ${c.word_count_target}\n- Outline: ${(c.outline || []).join(', ')}`).join('\n') || 'N/A'}

## 🔗 Backlink Strategy
### Overview
${bs?.overview || 'N/A'}

### 5 Target Sites
${bs?.target_sites?.map((s: any) => `- ${s.site} (${s.type}) – ${s.reason}. Contact: ${s.contact_method}`).join('\n') || 'None'}

### Guest Post Topics
${bs?.guest_post_topics?.map((t: string) => `- ${t}`).join('\n') || 'None'}

### Broken Link Opportunities
${bs?.broken_link_opportunities?.map((b: string) => `- ${b}`).join('\n') || 'None'}

### Resource Pages
${bs?.resource_page_targets?.map((r: string) => `- ${r}`).join('\n') || 'None'}

### 📧 Outreach Email
\`\`\`
${bs?.outreach_email_template || 'N/A'}
\`\`\`

## ✅ On-Page Checklist
${analysis.onpage_checklist?.map((i: string, n: number) => `${n+1}. ${i}`).join('\n') || 'N/A'}

*Generated by MarketMuse AI PRO MAX ULTRA – $99/report*`;
}

export const createSEOReport = async (req: Request, res: Response, next: NextFunction) => {
  try {
    const { niche, country } = seoReportSchema.parse(req.body);
    const countryUpper = country.toUpperCase();
    const cacheKey = `seo_report_${niche}_${country}`;
    const cached = cacheService.get(cacheKey);
    if (cached) { console.log('📦 Returning cached'); return res.json(cached); }

    console.log(`🔍 SEO research: "${niche}" in ${countryUpper}`);
    const [searchData, keywordSuggestions, trendsData] = await Promise.all([
      getSearchResults(niche, country), getKeywordSuggestions(niche, country), getTrends(niche, countryUpper)
    ]);

    const serpOrganic = (searchData as any).organic_results?.slice(0, 5).map((r: any) => ({
      position: r.position, title: r.title, url: r.link, snippet: r.snippet || ''
    })) || [];

    const userMessage = `Niche: ${niche}\nCountry: ${country}\nSERP: ${JSON.stringify(serpOrganic)}\nRelated: ${JSON.stringify(keywordSuggestions.slice(0, 10))}\nTrends: ${JSON.stringify(trendsData.slice(0, 6))}\nReturn JSON.`;

    console.log('🤖 Requesting Groq...');
    const groqResponse = await runGroqWithRetry(SEO_SYSTEM_PROMPT, userMessage);
    const analysis = extractJSON(groqResponse);

    if (!analysis.keywords) throw new Error('Missing keywords');
    const markdown = generateSEOMarkdown(analysis, niche, country);

    const report = await Report.create({ type: 'seo', niche, country, value: '$99', data: analysis, markdown, charts: {} });
    console.log('✅ SEO report:', report._id);

    const result = { id: report._id, type: report.type, niche, country, value: '$99', data: analysis, markdown, createdAt: report.createdAt };
    cacheService.set(cacheKey, result, 86400);
    return res.status(201).json(result);
  } catch (err) {
    if (err instanceof ZodError) return res.status(400).json({ error: 'Validation failed', details: err.errors });
    next(err);
  }
};

export const getSEOReport = async (req: Request, res: Response, next: NextFunction) => {
  try {
    const report = await Report.findById(req.params.id);
    if (!report || report.type !== 'seo') return res.status(404).json({ error: 'Not found' });
    res.json(report);
  } catch (err) { next(err); }
};
